version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  webserver:
    build: .
    container_name: airflow-webserver
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/app/scripts
      - ./data:/app/data
      - ./logs:/app/logs
      - ./tests:/opt/airflow/tests
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW_SECRET_KEY}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init &&
      airflow users create --username admin --firstname Luiz --lastname Milare --role Admin --email admin@example.com --password admin &&
      airflow webserver"

  scheduler:
    build: .
    container_name: airflow-scheduler
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/app/scripts
      - ./data:/app/data
      - ./logs:/app/logs
      - ./tests:/opt/airflow/tests
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW_SECRET_KEY}
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    command: scheduler