apiVersion: 1

datasources:
  - name: AirflowPostgres
    type: postgres
    uid: my-postgres-db
    url: airflow-postgres:5432
    user: ${POSTGRES_USER}
    database: ${POSTGRES_DB}
    isDefault: true
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: 'disable'
      postgresVersion: 1300
      dbmode: 'postgres'
    secureJsonData:
      password: ${POSTGRES_PASSWORD}